service: Game
plugins:
  - serverless-webpack
  - serverless-dynamodb-autoscaling
  - serverless-prune-plugin
provider:
  name: aws
  runtime: nodejs6.10
  region: ap-southeast-1
  memorySize: 256
  environment:
      TOKEN_SECRET: ${ssm:TOKEN_SECRET~true}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
        # - dynamodb:DescribeTable
        # - dynamodb:Query
        # - dynamodb:Scan
        # - dynamodb:GetItem
        # - dynamodb:PutItem
        # - dynamodb:BatchWriteItem
        # - dynamodb:UpdateItem
        # - dynamodb:DeleteItem
      Resource:
          Fn::Join:
          - ''
          - - 'arn:aws:dynamodb:'
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":table/*"
custom:
  webpackIncludeModules: true
  capacities: #数据库自动扩容
    - table: HeraGameRecord
      index:
        - parentIdIndex
        - CreatedDateIndex
      read:
        minimum: ${ssm:MIN_STORE_UNIT}
        maximum: 10000
        usage: 0.75
      write:
        minimum: ${ssm:MIN_STORE_UNIT}
        maximum: 10000
        usage: 0.75
    - table: HeraGamePlayer
      index:
        - userIdIndex
      read:
        minimum: ${ssm:MIN_STORE_UNIT}
        maximum: 10000
        usage: 0.75
      write:
        minimum: ${ssm:MIN_STORE_UNIT}
        maximum: 10000
        usage: 0.75
    - table: SYSToken
      read:
        minimum: ${ssm:SMALL_STORE_UNIT}
        maximum: 10000
        usage: 0.75
      write:
        minimum: ${ssm:SMALL_STORE_UNIT}
        maximum: 10000
        usage: 0.75
    - table: BillStat
      index:
        - CreatedDateIndex
        - roleDateIndex
        - roleTypeIndex
        - userIdAndDate
      read:
        minimum: 10
        maximum: 10000
        usage: 0.75
      write:
        minimum: 10
        maximum: 10000
        usage: 0.75
    - table: HawkeyePlayerEmailRecord
      index:
        - CreatedDateIndex
      read:
        minimum: ${ssm:SMALL_STORE_UNIT}
        maximum: 10000
        usage: 0.75
      write:
        minimum: ${ssm:SMALL_STORE_UNIT}
        maximum: 10000
        usage: 0.75
    - table: PlayerBillDetail
      index:
        - UserNameIndex
        - BillIdIndex
      read:
        minimum: ${ssm:MIN_STORE_UNIT}
        maximum: 10000
        usage: 0.75
      write:
        minimum: ${ssm:BIG_STORE_UNIT}
        maximum: 10000
        usage: 0.75
functions:
  tokenVerify:
    handler: api.jwtverify
    integration: lambda
  # 触发器开始
  billDetailTrigger: #玩家流水触发器
    handler: api_trigger.billDetailTrigger
    events:
      - stream:
          type: dynamodb
          arn:
            Fn::GetAtt:
              - PlayerBillDetail
              - StreamArn
resources:
  Resources:
    HawkeyePlayerEmailRecord: #玩家接收邮件记录表
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: HawkeyePlayerEmailRecord
        AttributeDefinitions:
          -
            AttributeName: userId
            AttributeType: N
          -
            AttributeName: emid
            AttributeType: S
          -
            AttributeName: createdDate
            AttributeType: S
        KeySchema:
          -
            AttributeName: userId
            KeyType: HASH
          -
            AttributeName: emid
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: ${ssm:SMALL_STORE_UNIT}
          WriteCapacityUnits: ${ssm:SMALL_STORE_UNIT}
        GlobalSecondaryIndexes:
          -
            IndexName: CreatedDateIndex
            KeySchema:
            -
              AttributeName: createdDate
              KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: ${ssm:SMALL_STORE_UNIT}
              WriteCapacityUnits: ${ssm:SMALL_STORE_UNIT}

    HeraGamePlayer: #玩家表
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: HeraGamePlayer
        AttributeDefinitions:
          -
            AttributeName: userName
            AttributeType: S
          -
            AttributeName: userId
            AttributeType: N
        KeySchema:
          -
            AttributeName: userName
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: ${ssm:MIN_STORE_UNIT}
          WriteCapacityUnits: ${ssm:MIN_STORE_UNIT}
        GlobalSecondaryIndexes:
          -
            IndexName: userIdIndex
            KeySchema:
              -
                AttributeName: userId
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: ${ssm:SMALL_STORE_UNIT}
              WriteCapacityUnits: ${ssm:MIN_STORE_UNIT}

    HeraGameRecord: #游戏战绩表
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: HeraGameRecord
        AttributeDefinitions:
          -
            AttributeName: userName
            AttributeType: S
          -
            AttributeName: betId
            AttributeType: S
          -
            AttributeName: parentId
            AttributeType: S
          -
            AttributeName: betTime
            AttributeType: N
          -
            AttributeName: createdDate
            AttributeType: S
        KeySchema:
          -
            AttributeName: userName
            KeyType: HASH
          -
            AttributeName: betId
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: ${ssm:MIN_STORE_UNIT}
          WriteCapacityUnits: ${ssm:MIN_STORE_UNIT}
        GlobalSecondaryIndexes:
          -
            IndexName: parentIdIndex
            KeySchema:
              -
                AttributeName: parentId
                KeyType: HASH
              -
                AttributeName: betTime
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: ${ssm:MIN_STORE_UNIT}
              WriteCapacityUnits: ${ssm:MIN_STORE_UNIT}
          -
            IndexName: CreatedDateIndex
            KeySchema:
              -
                AttributeName: createdDate
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: ${ssm:MIN_STORE_UNIT}
              WriteCapacityUnits: ${ssm:MIN_STORE_UNIT}

    BillStat: #统计表
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: BillStat
        AttributeDefinitions:
          -
            AttributeName: sn
            AttributeType: S
          -
            AttributeName: userId
            AttributeType: S
          -
            AttributeName: dateStr
            AttributeType: S
          -
            AttributeName: role
            AttributeType: S
          -
            AttributeName: type
            AttributeType: N
          -
            AttributeName: createdDate
            AttributeType: S
        KeySchema:
          -
            AttributeName: sn
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 10
          WriteCapacityUnits: 10
        GlobalSecondaryIndexes:
          -
            IndexName: CreatedDateIndex
            KeySchema:
            -
              AttributeName: createdDate
              KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 10
              WriteCapacityUnits: 10
          -
            IndexName: roleDateIndex
            KeySchema:
              -
                AttributeName: role
                KeyType: HASH
              -
                AttributeName: dateStr
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 10
              WriteCapacityUnits: 10
          -
            IndexName: roleTypeIndex
            KeySchema:
              -
                AttributeName: role
                KeyType: HASH
              -
                AttributeName: type
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 10
              WriteCapacityUnits: 10
          -
            IndexName: userIdAndDate
            KeySchema:
              -
                AttributeName: userId
                KeyType: HASH
              -
                AttributeName: dateStr
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 10
              WriteCapacityUnits: 10

    SYSToken: #用户登录令牌表
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: SYSToken
        AttributeDefinitions:
          -
            AttributeName: userId
            AttributeType: S
        KeySchema:
          -
            AttributeName: userId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: ${ssm:SMALL_STORE_UNIT}
          WriteCapacityUnits: ${ssm:SMALL_STORE_UNIT}
    SYSRolePermission: #子角色权限表
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: SYSRolePermission
        AttributeDefinitions:
          -
            AttributeName: name
            AttributeType: S
        KeySchema:
          -
            AttributeName: name
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: ${ssm:SMALL_STORE_UNIT}
          WriteCapacityUnits: ${ssm:SMALL_STORE_UNIT}

    SYSCacheBalance: #用户余额缓存表
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: SYSCacheBalance
        AttributeDefinitions:
          -
            AttributeName: userId
            AttributeType: S
          -
            AttributeName: type
            AttributeType: S
        KeySchema:
          -
            AttributeName: userId
            KeyType: HASH
          -
            AttributeName: type
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: ${ssm:SMALL_STORE_UNIT}
          WriteCapacityUnits: ${ssm:SMALL_STORE_UNIT}
    PlayerBillDetail: #玩家账单明细表
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: PlayerBillDetail
        AttributeDefinitions:
          -
            AttributeName: sn
            AttributeType: S
          -
            AttributeName: userName
            AttributeType: S
          -
            AttributeName: createdAt
            AttributeType: N
          -
            AttributeName: billId
            AttributeType: S
        KeySchema:
          -
            AttributeName: sn
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: ${ssm:SMALL_STORE_UNIT}
          WriteCapacityUnits: ${ssm:BIG_STORE_UNIT}
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
        GlobalSecondaryIndexes:
          -
            IndexName: UserNameIndex
            KeySchema:
              -
                AttributeName: userName
                KeyType: HASH
              -
                AttributeName: createdAt
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: ${ssm:MIN_STORE_UNIT}
              WriteCapacityUnits: ${ssm:BIG_STORE_UNIT}
          -
            IndexName: BillIdIndex
            KeySchema:
              -
                AttributeName: billId
                KeyType: HASH
              -
                AttributeName: createdAt
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: ${ssm:MIN_STORE_UNIT}
              WriteCapacityUnits: ${ssm:BIG_STORE_UNIT}
    UserRankStat: #用户排行榜
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: UserRankStat
        AttributeDefinitions:
          -
            AttributeName: userName
            AttributeType: S
          # -
          #   AttributeName: balance
          #   AttributeType: N
          # -
          #   AttributeName: bet
          #   AttributeType: N
          # -
          #   AttributeName: win
          #   AttributeType: N
        KeySchema:
          -
            AttributeName: userName
            KeyType: HASH
          # -
          #   AttributeName: balance
          #   KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 10
          WriteCapacityUnits: 10