
service: Stat
plugins:
  - serverless-webpack
  - serverless-secrets-plugin
custom:
  webpackIncludeModules: true
  secrets: ${file(secrets.${opt:stage, self:provider.stage}.yml)} #密钥文件
provider:
  name: aws
  runtime: nodejs6.10
  region: ap-southeast-1
  memorySize: 256
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:DescribeStream
        - dynamodb:GetRecords
        - dynamodb:GetShardIterator
        - dynamodb:ListStreams
      Resource: "arn:aws:dynamodb:ap-southeast-1:*:*"
functions:
  tokenAuth: #TOKEN验证
    handler: api.jwtverify
    environment:
      TOKEN_SECRET: ${self:custom.secrets.TOKEN_SECRET}
    integration: lambda
  #统计开始
  overview: #统计总览
    handler: api_sta.overview
    events:
      -
        http:
          path: /statistics/overview
          method: get
          cors: true
  salePointsInfo:  #本周本月统计
    handler: api_sta.salePointsInfo
    events:
      -
        http:
          path: /statistics/month/week
          method: get
          cors: true
  statisticsDetail:  #详情
    handler: api_sta.statisticsDetail
    events:
      -
        http:
          path: /statistics/detail
          method: get
          cors: true
  statisticsList:  #某一天的记录数据
    handler: api_sta.statisticsListByDay
    events:
      -
        http:
          path: /statistics/day/list
          method: get
          cors: true