service: StateMachine
plugins:
  - serverless-webpack
  - serverless-prune-plugin
  - serverless-step-functions
  # - serverless-secrets-plugin
provider:
  name: aws
  runtime: nodejs6.10
  # region: ap-northeast-1
  region: ap-southeast-1
  memorySize: 256
  environment:
      TOKEN_SECRET: ${ssm:TOKEN_SECRET~true}
      IMG_BUCKET: ${ssm:IMG_BUCKET}
  timeout: 300
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
          Fn::Join:
          - ''
          - - 'arn:aws:dynamodb:'
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":table/*"
    - Effect: Allow
      Action:
         - s3:*
      Resource:
        Fn::Join:
          - ''
          - - 'arn:aws:s3:::'
            - '*'
custom:
  webpackIncludeModules: true
  # secrets: ${file(secrets.${opt:stage, self:provider.stage}.yml)} #密钥文件
functions:
  tokenAuth: #TOKEN验证
    handler: api.jwtverify
    integration: lambda
  # upload: #上传文件至S3
  #   handler: api_upload.upload
  #   events:
  #       - http:
  #           path: upload
  #           method: post
  #           cors: true
  #           authorizer: tokenAuth      
  # backup: #备份数据库
  #   handler: api_backup.backup
  #   events:
  #       - http:
  #           path: /backup
  #           method: post
  #           cors: true
  #           authorizer: tokenAuth
  # restore: #恢复数据库
  #   handler: api_backup.restore
  #   events:
  #       - http:
  #           path: /restore
  #           method: post
  #           cors: true
  #           authorizer: tokenAuth
  # incBackup: #增量备份数据库
  #   memorySize: 1536
  #   handler: api_backup.incBackup
  #   events:
  #       - http:
  #           path: /incBackup
  #           method: post
  #           cors: true
  #           authorizer: tokenAuth
# stepFunctions:
#   stateMachines:
#     backup:
#       events:
#         - http:
#             path: /backup
#             method: post
#             cors: true
#             authorizer: tokenAuth
#       name: backupStateMachine
#       definition:
#         Comment: "备份数据库"
#         StartAt: BackupStart
#         States:
#           BackupStart:
#             Type: Task
#             Resource: arn:aws:lambda:${opt:region}:${self:custom.secrets.ACCOUNT_ID}:function:${self:service}-${opt:stage}-backup
#             End: true
# resources:
#   Resources:
#     TEST:
#         Type: AWS::DynamoDB::Table
#         DeletionPolicy: Retain
#         Properties:
#           TableName: TEST
#           AttributeDefinitions:
#             -
#               AttributeName: testId
#               AttributeType: S
#           KeySchema:
#             -
#               AttributeName: testId
#               KeyType: HASH
#           ProvisionedThroughput:
#             ReadCapacityUnits: ${ssm:MIN_STORE_UNIT}
#             WriteCapacityUnits: ${ssm:MIN_STORE_UNIT}