service: Hawkeye
plugins:
  - serverless-webpack
  - serverless-prune-plugin
custom:
  webpackIncludeModules: true
provider:
  name: aws
  runtime: nodejs6.10
  region: ap-southeast-1
  memorySize: 256
  environment:
      TOKEN_SECRET: ${ssm:TOKEN_SECRET~true}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:BatchWriteItem
      Resource:
          Fn::Join:
          - ''
          - - 'arn:aws:dynamodb:'
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":table/*"  
functions:
  tokenVerify:
    handler: billApi.jwtverify
    integration: lambda
  addNotice:  #添加公告
    handler: noticeApi.add
    events:
      - http:
          path: /notice/add
          method: post
          cors: true
          authorizer: tokenVerify