
service: Hawkeye # NOTE: update this with your service name

# Use the serverless-webpack plugin to transpile ES6
plugins:
  - serverless-webpack

# Enable auto-packing of external modules
custom:
  webpackIncludeModules: true


provider:
  name: aws
  runtime: nodejs6.10
  region: ap-southeast-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:ap-southeast-1:*:*"
functions:
  tokenVerify:
    handler: noticeApi.jwtverify
    integration: lambda
  addNotice:  #添加公告
    handler: noticeApi.add
    events:
      - http:
          path: /notice/add
          method: post
          cors: true
          authorizer: tokenVerify
  updateNotice:  #修改公告
    handler: noticeApi.update
    events:
      - http:
          path: /notice/update
          method: post
          cors: true
          authorizer: tokenVerify
  removeNotice:  #删除公告
    handler: noticeApi.remove
    events:
      - http:
          path: /notice/remove
          method: post
          cors: true
          authorizer: tokenVerify
  listNotice:  #公告列表
    handler: noticeApi.list
    events:
      - http:
          path: /notice/list
          method: post
          cors: true
          authorizer: tokenVerify
  merchantList :  #商家列表
    handler: noticeApi.merchantList
    events:
      - http:
          path: /notice/merchant/list
          method: post
          cors: true
          authorizer: tokenVerify
  playerList :  #玩家列表
    handler: playerManagerApi.playerList
    events:
      - http:
          path: /player/list
          method: post
          cors: true
          authorizer: tokenVerify
  info :  #公告信息
    handler: openApi.info
    events:
      - http:
          path: /notice/info
          method: post
          cors: true
  emailInfo :  #邮件信息
    handler: openApi.emailInfo
    events:
      - http:
          path: /email/info
          method: post
          cors: true
  addEmail:  #添加邮件
    handler: emailApi.add
    events:
      - http:
          path: /email/add
          method: post
          cors: true
          authorizer: tokenVerify
  updateEmail:  #修改邮件
    handler: emailApi.update
    events:
      - http:
          path: /email/update
          method: post
          cors: true
          authorizer: tokenVerify
  removeEmail:  #删除邮件
    handler: emailApi.remove
    events:
      - http:
          path: /email/remove
          method: post
          cors: true
          authorizer: tokenVerify
  acceptMail:  #接收邮件
    handler: openApi.acceptMail
    events:
      - http:
          path: /email/accept
          method: post
          cors: true
  listEmail:  #邮件列表
    handler: emailApi.list
    events:
      - http:
          path: /email/list
          method: post
          cors: true
          authorizer: tokenVerify
  gameToolList :  #道具列表
    handler: emailApi.toolList
    events:
      - http:
          path: /email/tool/list
          method: post
          cors: true
          authorizer: tokenVerify
  toolList:  #道具列表
    handler: openApi_tool.toolList
    events:
      - http:
          path: /game/tool/list
          method: get
          cors: true
  seatList:  #席位列表
    handler: openApi_tool.seatList
    events:
      - http:
          path: /game/seat/list
          method: get
          cors: true
  packageList:  #道具包列表
    handler: openApi_tool.packageList
    events:
      - http:
          path: /game/package/list
          method: get
          cors: true
  buy:  #购买道具
    handler: openApi_tool.playerBuyProp
    events:
      - http:
          path: /game/prop/buy
          method: post
          cors: true
  buyDiamonds:  #购买钻石
    handler: openApi_tool.playerBuyDiamonds
    events:
      - http:
          path: /game/diamonds/buy
          method: post
          cors: true
  advertList:  #广告列表
    handler: openApi_ad.advertList
    events:
      - http:
          path: /game/advert/list
          method: get
          cors: true
resources:
  Resources:
    HawkeyePlayerEmailRecord: #玩家接收邮件记录
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: HawkeyePlayerEmailRecord
        AttributeDefinitions:
          -
            AttributeName: userId
            AttributeType: N
          -
            AttributeName: emid
            AttributeType: S
        KeySchema:
          -
            AttributeName: userId
            KeyType: HASH
          -
            AttributeName: emid
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1