
service: Hawkeye # NOTE: update this with your service name

# Use the serverless-webpack plugin to transpile ES6
plugins:
  - serverless-webpack

# Enable auto-packing of external modules
custom:
  webpackIncludeModules: true


provider:
  name: aws
  runtime: nodejs6.10
  region: ap-southeast-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:ap-southeast-1:*:*"
functions:
  tokenVerify:
    handler: noticeApi.jwtverify
    integration: lambda
  addNotice:  #添加公告
    handler: noticeApi.add
    events:
      - http:
          path: /notice/add
          method: post
          cors: true
          authorizer: tokenVerify
  updateNotice:  #修改公告
    handler: noticeApi.update
    events:
      - http:
          path: /notice/update
          method: post
          cors: true
          authorizer: tokenVerify
  removeNotice:  #删除公告
    handler: noticeApi.remove
    events:
      - http:
          path: /notice/remove
          method: post
          cors: true
          authorizer: tokenVerify
  listNotice:  #公告列表
    handler: noticeApi.list
    events:
      - http:
          path: /notice/list
          method: post
          cors: true
          authorizer: tokenVerify
  merchantList :  #商家列表
    handler: noticeApi.merchantList
    events:
      - http:
          path: /notice/merchant/list
          method: post
          cors: true
          authorizer: tokenVerify
  info :  #公告信息
    handler: openApi.info
    events:
      - http:
          path: /notice/info
          method: post
          cors: true
  emailInfo :  #邮件信息
    handler: openApi.emailInfo
    events:
      - http:
          path: /email/info
          method: post
          cors: true
  addEmail:  #添加邮件
    handler: emailApi.add
    events:
      - http:
          path: /email/add
          method: post
          cors: true
          authorizer: tokenVerify
  updateEmail:  #修改邮件
    handler: emailApi.update
    events:
      - http:
          path: /email/update
          method: post
          cors: true
          authorizer: tokenVerify
  removeEmail:  #删除邮件
    handler: emailApi.remove
    events:
      - http:
          path: /email/remove
          method: post
          cors: true
          authorizer: tokenVerify
  listEmail:  #邮件列表
    handler: emailApi.list
    events:
      - http:
          path: /email/list
          method: post
          cors: true
          authorizer: tokenVerify
  toolList :  #道具列表
    handler: emailApi.toolList
    events:
      - http:
          path: /email/tool/list
          method: post
          cors: true
          authorizer: tokenVerify