
service: Hawkeye # NOTE: update this with your service name

# Use the serverless-webpack plugin to transpile ES6
plugins:
  - serverless-webpack

# Enable auto-packing of external modules
custom:
  webpackIncludeModules: true


provider:
  name: aws
  runtime: nodejs6.10
  region: ap-southeast-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:ap-southeast-1:*:*"
functions:
  tokenVerify:
    handler: noticeApi.jwtverify
    integration: lambda
  addNotice:  #添加公告
    handler: noticeApi.add
    events:
      - http:
          path: /notice/add
          method: post
          cors: true
          authorizer: tokenVerify
  updateNotice:  #修改公告
    handler: noticeApi.update
    events:
      - http:
          path: /notice/update
          method: post
          cors: true
          authorizer: tokenVerify
  removeNotice:  #删除公告
    handler: noticeApi.remove
    events:
      - http:
          path: /notice/remove
          method: post
          cors: true
          authorizer: tokenVerify
  listNotice:  #公告列表
    handler: noticeApi.list
    events:
      - http:
          path: /notice/list
          method: post
          cors: true
          authorizer: tokenVerify
  merchantList :  #商家列表
    handler: noticeApi.merchantList
    events:
      - http:
          path: /notice/merchant/list
          method: post
          cors: true
          authorizer: tokenVerify