
service: Diana # NOTE: update this with your service name

# Use the serverless-webpack plugin to transpile ES6
plugins:
  - serverless-webpack

# Enable auto-packing of external modules
custom:
  webpackIncludeModules: true


provider:
  name: aws
  runtime: nodejs6.10
  region: ap-southeast-1
  iamRoleStatements:
      -
        Effect: Allow
        Action:
          - dynamodb:GetItem
          - dynamodb:PutItem
          - dynamodb:Query
          - dynamodb:UpdateItem
          - dynamodb:DeleteItem
          - dynamodb:BatchWriteItem
          - dynamodb:Scan
        Resource:
          Fn::Join:
          - ''
          - - 'arn:aws:dynamodb:'
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":table/Zeus*"
          

functions:
  tokenAuth:
    handler: api.jwtverify
    integration: lambda

  gameNew:
    handler: api.gameNew
    events:
      -
        http:
          path: games
          method: post
          cors: true
  gameList:
    handler: api.gameList
    events:
      -
        http:
          path: games/{gameType}
          method: get
          cors: true
  depositPoints:
    handler: api.depositPoints
    events:
      -
        http:
          path: deposit_points
          method: post
          cors: true
          authorizer: tokenAuth
  withdrawPoints:
    handler: api.withdrawPoints
    events:
      -
        http:
          path: withdraw_points
          method: post
          cors: true
          authorizer: tokenAuth
  billOne:
    handler: api.billOne
    events:
      -
        http:
          path: bills/{userId}
          method: get
          cors: true
          authorizer: tokenAuth
  billList:
    handler: api.billList
    events:
      -
        http:
          path: waterfall/{userId}
          method: get
          cors: true
          authorizer: tokenAuth
  logList: #日志列表，接口编号：
    handler: api.logList
    events:
      -
        http:
          path: logList
          method: post
          cors: true
          authorizer: tokenAuth
  helpGenreList: 
    handler: api_server.helpGenreList
    events:
      -
        http:
          path: /help/genres/{userId}
          method: get
          cors: true
          authorizer: tokenAuth
  helpCreateGenre: 
    handler: api_server.createHelpGenre
    events:
      -
        http:
          path: /help/genre/create/{userId}
          method: post
          cors: true
          authorizer: tokenAuth
  createHelp: 
    handler: api_server.createHelp
    events:
      -
        http:
          path: /help/create
          method: post
          cors: true
          authorizer: tokenAuth
resources:
  Resources:
    ZeusPlatformHelp:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ZeusPlatformHelp
        AttributeDefinitions:
          -
            AttributeName: sn
            AttributeType: S
          -
            AttributeName: userId
            AttributeType: S
        KeySchema:
          -
            AttributeName: sn
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
          -
            IndexName: userIdIndex
            KeySchema:
              -
                AttributeName: userId
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1