
service: Diana
plugins:
  - serverless-webpack
custom:
  webpackIncludeModules: true

provider:
  name: aws
  runtime: nodejs6.10
  region: ap-southeast-1
  iamRoleStatements:
      -
        Effect: Allow
        Action:
          - dynamodb:GetItem
          - dynamodb:PutItem
          - dynamodb:Query
          - dynamodb:UpdateItem
          - dynamodb:DeleteItem
          - dynamodb:BatchWriteItem
          - dynamodb:Scan
        Resource:
          Fn::Join:
          - ''
          - - 'arn:aws:dynamodb:'
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":table/*"
          
functions:
  tokenAuth:
    handler: api.jwtverify
    integration: lambda
  # ==================== 以下是账单和日志接口服务 ====================
  billTransfer: # 转账
    handler: api.billTransfer
    events:
      -
        http:
          path: billTransfer
          method: post
          cors: true
          authorizer: tokenAuth
  billOne: # 单个账单
    handler: api.billOne
    events:
      -
        http:
          path: bills/{userId}
          method: get
          cors: true
          authorizer: tokenAuth
  billList: # 账单列表
    handler: api.billList
    events:
      -
        http:
          path: waterfall/{userId}
          method: get
          cors: true
          authorizer: tokenAuth
  logList: #日志列表
    handler: api.logList
    events:
      -
        http:
          path: logList
          method: post
          cors: true
          authorizer: tokenAuth
  # ==================== 以下是游戏管理接口服务 ====================
  gameNew: #创建游戏
    handler: api_game.gameNew
    events:
      -
        http:
          path: games
          method: post
          cors: true
          authorizer: tokenAuth
  gameList: #游戏列表
    handler: api_game.gameList
    events:
      -
        http:
          path: gameList
          method: post
          cors: true
          authorizer: tokenAuth
  gameOne: #单个游戏
    handler: api_game.gameOne
    events:
      -
        http:
          path: gameOne/{gameType}/{gameId}
          method: get
          cors: true
          authorizer: tokenAuth
  gameChangeStatus: #变更游戏状态
    handler: api_game.gameChangeStatus
    events:
      -
        http:
          path: gameChangeStatus
          method: post
          cors: true
          authorizer: tokenAuth
  # ==================== 以下是游戏厂商接口服务 ====================
  companyNew: #创建游戏厂商
    handler: api_company.companyNew
    events:
      -
        http:
          path: companyNew
          method: post
          cors: true
          authorizer: tokenAuth
  companyList: #游戏厂商列表
    handler: api_company.companyList
    events:
      -
        http:
          path: companyList
          method: post
          cors: true
          authorizer: tokenAuth
  companyOne: #单个厂商
    handler: api_company.companyOne
    events:
      -
        http:
          path: companyOne/{companyName}/{companyId}
          method: get
          cors: true
          authorizer: tokenAuth
  companyChangeStatus: #变更厂商状态
    handler: api_company.companyChangeStatus
    events:
      -
        http:
          path: companyChangeStatus
          method: post
          cors: true
          authorizer: tokenAuth
  # ==================== 以下是道具管理接口服务 ====================
  toolNew: #创建道具
    handler: api_tool.toolNew
    events:
      -
        http:
          path: toolNew
          method: post
          cors: true
          authorizer: tokenAuth
  toolList: #道具列表
    handler: api_tool.toolList
    events:
      -
        http:
          path: toolList
          method: post
          cors: true
          authorizer: tokenAuth
  toolOne: #单个道具
    handler: api_tool.toolOne
    events:
      -
        http:
          path: toolOne
          method: post
          cors: true
          authorizer: tokenAuth
  toolChangeStatus: #变更道具状态
    handler: api_tool.toolChangeStatus
    events:
      -
        http:
          path: toolChangeStatus
          method: post
          cors: true
          authorizer: tokenAuth
  toolUpdate: #道具更新
    handler: api_tool.toolUpdate
    events:
      -
        http:
          path: toolUpdate
          method: post
          cors: true
          authorizer: tokenAuth
  # ==================== 以下是帮助中心接口服务 ====================
  helpGenreList: 
    handler: api_server.helpGenreList
    events:
      -
        http:
          path: /help/genres
          method: get
          cors: true
          authorizer: tokenAuth
  helpCreateGenre: 
    handler: api_server.createHelpGenre
    events:
      -
        http:
          path: /help/genre/create
          method: post
          cors: true
          authorizer: tokenAuth
  createHelp: 
    handler: api_server.createHelp
    events:
      -
        http:
          path: /help/create
          method: post
          cors: true
          authorizer: tokenAuth