
service: Diana # NOTE: update this with your service name

# Use the serverless-webpack plugin to transpile ES6
plugins:
  - serverless-webpack

# Enable auto-packing of external modules
custom:
  webpackIncludeModules: true


provider:
  name: aws
  runtime: nodejs6.10
  region: ap-southeast-1
  iamRoleStatements:
      -
        Effect: Allow
        Action:
          - dynamodb:GetItem
          - dynamodb:PutItem
          - dynamodb:Query
          - dynamodb:UpdateItem
          - dynamodb:DeleteItem
          - dynamodb:BatchWriteItem
          - dynamodb:Scan
        Resource:
          Fn::Join:
          - ''
          - - 'arn:aws:dynamodb:'
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":table/Zeus*"
          

functions:
  tokenAuth:
    handler: api.jwtverify
    integration: lambda

  gameNew:
    handler: api.gameNew
    events:
      -
        http:
          path: games
          method: post
          cors: true
          authorizer: tokenAuth
  gameList:
    handler: api.gameList
    events:
      -
        http:
          path: gameList
          method: post
          cors: true
          authorizer: tokenAuth
  gameOne:
    handler: api.gameOne
    events:
      -
        http:
          path: gameOne/{gameType}/{gameId}
          method: get
          cors: true
          authorizer: tokenAuth
  gameChangeStatus: 
    handler: api.gameChangeStatus
    events:
      -
        http:
          path: gameChangeStatus
          method: post
          cors: true
          authorizer: tokenAuth
  billTransfer:
    handler: api.billTransfer
    events:
      -
        http:
          path: billTransfer
          method: post
          cors: true
          authorizer: tokenAuth
  billOne:
    handler: api.billOne
    events:
      -
        http:
          path: bills/{userId}
          method: get
          cors: true
          authorizer: tokenAuth
  billList:
    handler: api.billList
    events:
      -
        http:
          path: waterfall/{userId}
          method: get
          cors: true
          authorizer: tokenAuth
  logList: #日志列表，接口编号：
    handler: api.logList
    events:
      -
        http:
          path: logList
          method: post
          cors: true
          authorizer: tokenAuth
  companyNew:
    handler: api.companyNew
    events:
      -
        http:
          path: companyNew
          method: post
          cors: true
          authorizer: tokenAuth
  companyList:
    handler: api.companyList
    events:
      -
        http:
          path: companyList
          method: post
          cors: true
          authorizer: tokenAuth
  companyOne:
    handler: api.companyOne
    events:
      -
        http:
          path: companyOne/{companyName}/{companyId}
          method: get
          cors: true
          authorizer: tokenAuth
  companyChangeStatus:
    handler: api.companyChangeStatus
    events:
      -
        http:
          path: companyChangeStatus
          method: post
          cors: true
          authorizer: tokenAuth
  helpGenreList: 
    handler: api_server.helpGenreList
    events:
      -
        http:
          path: /help/genres
          method: get
          cors: true
          authorizer: tokenAuth
  helpCreateGenre: 
    handler: api_server.createHelpGenre
    events:
      -
        http:
          path: /help/genre/create
          method: post
          cors: true
          authorizer: tokenAuth
  createHelp: 
    handler: api_server.createHelp
    events:
      -
        http:
          path: /help/create
          method: post
          cors: true
          authorizer: tokenAuth
  # depositPoints:
  #   handler: api.depositPoints
  #   events:
  #     -
  #       http:
  #         path: deposit_points
  #         method: post
  #         cors: true
  #         authorizer: tokenAuth
  # withdrawPoints:
  #   handler: api.withdrawPoints
  #   events:
  #     -
  #       http:
  #         path: withdraw_points
  #         method: post
  #         cors: true
  #         authorizer: tokenAuth