
service: Hera # NOTE: update this with your service name

# Use the serverless-webpack plugin to transpile ES6
plugins:
  - serverless-webpack

# Enable auto-packing of external modules
custom:
  webpackIncludeModules: true


provider:
  name: aws
  runtime: nodejs6.10
  region: ap-southeast-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:ap-southeast-1:*:*"
functions:
  gamePlayerRegister:
    handler: openApi.gamePlayerRegister
    events:
      - http:
          path: /player/register
          method: post
          cors: true
  gamePlayerLogin:
    handler: openApi.gamePlayerLogin
    events:
      - http:
          path: /player
          method: post
          cors: true
  gamePlayerBalance:
    handler: openApi.gamePlayerBalance
    events:
      - http:
          path: /player/{username}/balance
          method: post
          cors: true
          #authorizer: tokenAuth
  getGamePlayerBalance:
    handler: openApi.getGamePlayerBalance
    events:
      - http:
          path: /player/{userName}/balance
          method: get
          cors: true
          #authorizer: tokenAuth
resources:
  Resources:
    HeraGamePlayer:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: HeraGamePlayer
        AttributeDefinitions:
          -
            AttributeName: userName
            AttributeType: S
        KeySchema:
          -
            AttributeName: userName
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    HeraGamePlayerBill:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: HeraGamePlayerBill
        AttributeDefinitions:
          -
            AttributeName: userName
            AttributeType: S
          -
            AttributeName: createAt
            AttributeType: N
        KeySchema:
          -
            AttributeName: userName
            KeyType: HASH
          -
            AttributeName: createAt
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
          -
            IndexName: userNameIndex
            KeySchema:
              -
                AttributeName: userName
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1