service: Hera
plugins:
  - serverless-webpack
custom:
  webpackIncludeModules: true
provider:
  name: aws
  runtime: nodejs6.10
  region: ap-southeast-1
  memorySize: 256
  timeout: 300
  environment:
      TOKEN_SECRET: ${ssm:TOKEN_SECRET~true}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
        # - dynamodb:DescribeTable
        # - dynamodb:Query
        # - dynamodb:Scan
        # - dynamodb:GetItem
        # - dynamodb:PutItem
        # - dynamodb:UpdateItem
        # - dynamodb:DeleteItem
        # - dynamodb:BatchWriteItem
        # - dynamodb:DescribeStream
        # - dynamodb:GetRecords
        # - dynamodb:GetShardIterator
        # - dynamodb:ListStreams
      Resource:
          Fn::Join:
          - ''
          - - 'arn:aws:dynamodb:'
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":table/*"
functions:
  tokenVerify:
    handler: managerApi.jwtverify
    integration: lambda
  gamePlayerRegister: #玩家注册
    handler: openApi.gamePlayerRegister
    events:
      - http:
          path: /player/register
          method: post
          cors: true
  gamePlayerLogin:     #玩家登陆
    handler: openApi.gamePlayerLogin
    events:
      - http:
          path: /player
          method: post
          cors: true
  updatePassword:     #玩家修改密码
    handler: openApi.updatePassword
    events:
      - http:
          path: /{userName}/password
          method: post
          cors: true
  updateInfo:     #玩家修改基本信息
    handler: openApi.updateUserInfo
    events:
      - http:
          path: /game/player/info
          method: post
          cors: true
  A3Login:     #玩家A3游戏登陆
    handler: openApi.gamePlayerA3Login
    events:
      - http:
          path: /game/login
          method: post
          cors: true
  gamePlayerBalance:    #玩家充值/提现
    handler: openApi.gamePlayerBalance
    events:
      - http:
          path: /player/{userName}/balance
          method: post
          cors: true
  getGamePlayerBalance:  #获取余额
    handler: openApi.getGamePlayerBalance
    events:
      - http:
          path: /player/{userName}/balance
          method: get
          cors: true
  A3Balance:  #获取A3余额
    handler: openApi.getA3GamePlayerBalance
    events:
      - http:
          path: /game/player/balance
          method: get
          cors: true
  gameRecord:  #游戏记录
    handler: openApi.playerGameRecord
    events:
      - http:
          path: /game/player/record
          method: post
          cors: true
  agentMix:  #代理洗码点
    handler: agentApi.agentMix
    events:
      - http:
          path: /agent/mix
          method: post
          cors: true
          authorizer: tokenVerify
  joinGame:  #玩家进入游戏
    handler: openApi.joinGame
    events:
      - http:
          path: /game/player/join
          method: post
          cors: true
  playerRecord:  #玩家记录验证
    handler: openApi.playerRecordValidate
    events:
      - http:
          path: /game/bill/verify
          method: post
          cors: true
  getGameRecord:  #获取玩家游戏记录
    handler: openApi.getPlayerGameRecord
    events:
      - http:
          path: /game/player/record/list
          method: post
          cors: true
  gamePlayerList:  #获取玩家列表
    handler: managerApi.gamePlayerList
    events:
      - http:
          path: /player/list
          method: get
          cors: true
          authorizer: tokenVerify
  gamePlayerInfo:  #玩家详情页面
    handler: managerApi.gamePlayerInfo
    events:
      - http:
          path: /player/bill/info
          method: get
          cors: true
          authorizer: tokenVerify
  gamePlayerForzen:  #冻结/解冻玩家 1解冻,2,冻结
    handler: managerApi.gamePlayerForzen
    events:
      - http:
          path: /player/forzen
          method: post
          cors: true
          authorizer: tokenVerify
  addPlayer:  #创建玩家
    handler: agentApi.createPlayer
    events:
      - http:
          path: /agent/player/create
          method: post
          cors: true
          authorizer: tokenVerify
  childrenAgent:  #下级代理
    handler: agentApi.childrenAgent
    events:
      - http:
          path: /agent/children/list
          method: post
          cors: true
          authorizer: tokenVerify
  agentPlayerList:  #代理玩家列表
    handler: agentApi.agentPlayerList
    events:
      - http:
          path: /agent/player/list
          method: post
          cors: true
          authorizer: tokenVerify
  agentPlayerDeposit:  #玩家取点
    handler: agentApi.agentPlayerQudian
    events:
      - http:
          path: /agent/player/take
          method: post
          cors: true
          authorizer: tokenVerify
  agentPlayerTake:  #玩家存点
    handler: agentApi.agentPlayerCudian
    events:
      - http:
          path: /agent/player/deposit
          method: post
          cors: true
          authorizer: tokenVerify
  updateAgentPassword:  #修改代理玩家密码
    handler: agentApi.updatePassword
    events:
      - http:
          path: /agent/player/password
          method: post
          cors: true
          authorizer: tokenVerify
  
  batchForzen:  #批量冻结/解冻玩家 1解冻,2,冻结
    handler: managerApi.batchForzen
    events:
      - http:
          path: /player/batch/forzen
          method: post
          cors: true
          authorizer: tokenVerify