
service: Hera # NOTE: update this with your service name

# Use the serverless-webpack plugin to transpile ES6
plugins:
  - serverless-webpack

# Enable auto-packing of external modules
custom:
  webpackIncludeModules: true


provider:
  name: aws
  runtime: nodejs6.10
  region: ap-southeast-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:ap-southeast-1:*:*"
functions:
  tokenVerify:
    handler: managerApi.jwtverify
    integration: lambda
  gamePlayerRegister: #玩家注册
    handler: openApi.gamePlayerRegister
    events:
      - http:
          path: /player/register
          method: post
          cors: true
  gamePlayerLogin:     #玩家登陆
    handler: openApi.gamePlayerLogin
    events:
      - http:
          path: /player
          method: post
          cors: true
  updatePassword:     #玩家修改密码
    handler: openApi.updatePassword
    events:
      - http:
          path: /{userName}/password
          method: post
          cors: true
  updateInfo:     #玩家修改基本信息
    handler: openApi.updateUserInfo
    events:
      - http:
          path: /game/player/info
          method: post
          cors: true
  A3Login:     #玩家A3游戏登陆
    handler: openApi.gamePlayerA3Login
    events:
      - http:
          path: /game/login
          method: post
          cors: true
  gamePlayerBalance:    #玩家充值/提现
    handler: openApi.gamePlayerBalance
    events:
      - http:
          path: /player/{userName}/balance
          method: post
          cors: true
  getGamePlayerBalance:  #获取余额
    handler: openApi.getGamePlayerBalance
    events:
      - http:
          path: /player/{userName}/balance
          method: get
          cors: true
  A3Balance:  #获取A3余额
    handler: openApi.getA3GamePlayerBalance
    events:
      - http:
          path: /game/player/balance
          method: get
          cors: true
  gameRecord:  #游戏记录
    handler: openApi.playerGameRecord
    events:
      - http:
          path: /game/player/record
          method: post
          cors: true
  joinGame:  #玩家进入游戏
    handler: openApi.joinGame
    events:
      - http:
          path: /game/player/join
          method: post
          cors: true
  toolList:  #道具列表
    handler: openApi_tool.toolList
    events:
      - http:
          path: /game/tool/list
          method: get
          cors: true
  seatList:  #席位列表列表
    handler: openApi_tool.seatList
    events:
      - http:
          path: /game/seat/list
          method: get
          cors: true
  packageList:  #道具包列表
    handler: openApi_tool.packageList
    events:
      - http:
          path: /game/package/list
          method: get
          cors: true
  buy:  #购买道具
    handler: openApi_tool.playerBuyProp
    events:
      - http:
          path: /game/prop/buy
          method: post
          cors: true
  buyDiamonds:  #购买钻石
    handler: openApi_tool.playerBuyDiamonds
    events:
      - http:
          path: /game/diamonds/buy
          method: post
          cors: true
  playerRecord:  #获取玩家记录验证
    handler: openApi.playerRecordValidate
    events:
      - http:
          path: /game/bill/verify
          method: post
          cors: true
  gamePlayerList:  #获取玩家列表
    handler: managerApi.gamePlayerList
    events:
      - http:
          path: /player/list
          method: get
          cors: true
          authorizer: tokenVerify
  gamePlayerInfo:  #玩家详情页面
    handler: managerApi.gamePlayerInfo
    events:
      - http:
          path: /player/bill/info
          method: get
          cors: true
          authorizer: tokenVerify
  gamePlayerForzen:  #冻结/解冻玩家 1解冻,2,冻结
    handler: managerApi.gamePlayerForzen
    events:
      - http:
          path: /player/forzen
          method: post
          cors: true
          authorizer: tokenVerify
  addPlayer:  #创建玩家
    handler: agentApi.createPlayer
    events:
      - http:
          path: /agent/player/create
          method: post
          cors: true
          authorizer: tokenVerify
  agentPlayerList:  #代理玩家列表
    handler: agentApi.agentPlayerList
    events:
      - http:
          path: /agent/player/list
          method: post
          cors: true
          authorizer: tokenVerify
  agentPlayerDeposit:  #玩家取点
    handler: agentApi.agentPlayerQudian
    events:
      - http:
          path: /agent/player/take
          method: post
          cors: true
          authorizer: tokenVerify
  agentPlayerTake:  #玩家存点
    handler: agentApi.agentPlayerCudian
    events:
      - http:
          path: /agent/player/deposit
          method: post
          cors: true
          authorizer: tokenVerify
  updateAgentPassword:  #修改代理玩家密码
    handler: agentApi.updatePassword
    events:
      - http:
          path: /agent/player/password
          method: post
          cors: true
          authorizer: tokenVerify
  
  batchForzen:  #批量冻结/解冻玩家 1解冻,2,冻结
    handler: managerApi.batchForzen
    events:
      - http:
          path: /player/batch/forzen
          method: post
          cors: true
          authorizer: tokenVerify
resources:
  Resources:
    HeraGamePlayer:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: HeraGamePlayer
        AttributeDefinitions:
          -
            AttributeName: userName
            AttributeType: S
          -
            AttributeName: userId
            AttributeType: N
        KeySchema:
          -
            AttributeName: userName
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
          -
            IndexName: userIdIndex
            KeySchema:
              -
                AttributeName: userId
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
    HeraGameRecord:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: HeraGameRecord
        AttributeDefinitions:
          -
            AttributeName: userName
            AttributeType: S
          -
            AttributeName: betId
            AttributeType: S
        KeySchema:
          -
            AttributeName: userName
            KeyType: HASH
          -
            AttributeName: betId
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1